> Inteligencia Computacional

#**APRENDISAJE NO SUPERVISADO:** REDUCCIÓN DE DIMENSIONES
---

**SEMESTRE:** VIII **GRUPO:** B

**ESTUDIANTES:** 
*   Nelson Yoel Phuño Cahuana          **- 170013**
*   Daysi Saimira Machaca Condori      **- 161989**










In [ ]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier

**Importar el data set desde una url logitud del sepalo, ancho del sépalo, largo de pétalo, ancho de pétalo y clases**

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)

**Mostrar nuestro conjunto de datos**

In [ ]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

##Preprocesamiento
**Se devide el conjunto de datos en un conjunto de caracteristicas y las etiquetas correspondientes**

In [ ]:
X = dataset.drop('Class', 1)
y = dataset['Class']

**Dividir los datos en conjuntos de prueba y entrenamiento.**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

**Realizaremos una normalización escalar estándar para normalizar nuestro conjunto de características**

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Aplicamos  PCA 
**1.  Inicialice la PCAclase pasando el número de componentes al constructor.**

**2. Llame a los métodos fity luego transformpasando el conjunto de características a estos métodos. El transformmétodo devuelve el número especificado de componentes principales.**


In [ ]:
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
#INDICE DE VARIANZA
explained_variance = pca.explained_variance_ratio_

**Entrenar nuestro algoritmo con 1 componente principal**

In [ ]:

pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

**Entrenado y haciendo predicciones  con la clasificacion de bosque aleatoria**

In [ ]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)
#Predicción de los resultados del conjunto de prueba
y_pred = classifier.predict(X_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
0.9333333333333333
